/**
 * Copyright (c) Paymium.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root of this projects source tree.
 */

import './globals.css';
import '@/types/unistyles';
import type { Metadata } from 'next';
import { Body } from '@/components/Body';
import { NavBar } from '@/components/NavBar';
import { PropsWithChildren, Suspense } from 'react';
import { ScrollView } from '@/components/ScrollView';
import { Footer } from '@/components/Footer';
import { Registry } from '@crossed/styled';
import { CrossedUIProvider } from '@crossed/ui/src';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: PropsWithChildren) {
  return (
    <html lang={'en'}>
      <head />
      <Registry>
        <CrossedUIProvider>
          <Body>
            <Suspense>
              <ScrollView
                stickyHeaderIndices={[0]}
                style={{ height: '100%' }}
                contentContainerStyle={{ minHeight: '100%' }}
              >
                <NavBar />
                {children}
                <Footer />
              </ScrollView>
            </Suspense>
          </Body>
        </CrossedUIProvider>
      </Registry>
    </html>
  );
}
