/**
 * Copyright (c) Paymium.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root of this projects source tree.
 */

export const countries = [
  {
    iso_alpha2: 'AF',
    iso_alpha3: 'AFG',
    accepted: false,
    card_partner_accepted: false,
    name_fr: 'Afghanistan',
    name_en: 'Afghanistan',
    name_es: 'Afganistán',
    name_de: 'Afghanistan',
    name_it: 'Afghanistan',
    telephone_code: 93,
  },
  {
    iso_alpha2: 'AX',
    iso_alpha3: 'ALA',
    accepted: true,
    card_partner_accepted: false,
    name_fr: 'Îles Aland',
    name_en: 'Åland Islands',
    name_es: 'Islas Åland',
    name_de: 'Åland',
    name_it: 'Isole Åland',
    telephone_code: null,
  },
  {
    iso_alpha2: 'AL',
    iso_alpha3: 'ALB',
    accepted: false,
    card_partner_accepted: false,
    name_fr: 'Albanie',
    name_en: 'Albania',
    name_es: 'Albania',
    name_de: 'Albanien',
    name_it: 'Albania',
    telephone_code: 355,
  },
  {
    iso_alpha2: 'DZ',
    iso_alpha3: 'DZA',
    accepted: true,
    card_partner_accepted: false,
    name_fr: 'Algérie',
    name_en: 'Algeria',
    name_es: 'Argelia',
    name_de: 'Algerien',
    name_it: 'Algeria',
    telephone_code: 213,
  },
  {
    iso_alpha2: 'AS',
    iso_alpha3: 'ASM',
    accepted: false,
    card_partner_accepted: false,
    name_fr: 'Samoa américaines',
    name_en: 'American Samoa',
    name_es: 'Samoa Americana',
    name_de: 'Amerikanisch-Samoa',
    name_it: 'Samoa Americane',
    telephone_code: 1684,
  },
  {
    iso_alpha2: 'AD',
    iso_alpha3: 'AND',
    accepted: true,
    card_partner_accepted: false,
    name_fr: 'Andorre',
    name_en: 'Andorra',
    name_es: 'Andorra',
    name_de: 'Andorra',
    name_it: 'Andorra',
    telephone_code: 376,
  },
  {
    iso_alpha2: 'AO',
    iso_alpha3: 'AGO',
    accepted: true,
    card_partner_accepted: false,
    name_fr: 'Angola',
    name_en: 'Angola',
    name_es: 'Angola',
    name_de: 'Angola',
    name_it: 'Angola',
    telephone_code: 244,
  },
  {
    iso_alpha2: 'AI',
    iso_alpha3: 'AIA',
    accepted: false,
    card_partner_accepted: false,
    name_fr: 'Anguilla',
    name_en: 'Anguilla',
    name_es: 'Anguila',
    name_de: 'Anguilla',
    name_it: 'Anguilla',
    telephone_code: 1264,
  },
  {
    iso_alpha2: 'AQ',
    iso_alpha3: 'ATA',
    accepted: true,
    card_partner_accepted: false,
    name_fr: 'Antarctique',
    name_en: 'Antarctica',
    name_es: 'Antártida',
    name_de: 'Antarktis',
    name_it: 'Antartide',
    telephone_code: 672,
  },
  {
    iso_alpha2: 'AG',
    iso_alpha3: 'ATG',
    accepted: true,
    card_partner_accepted: false,
    name_fr: 'Antigua-et-Barbuda',
    name_en: 'Antigua and Barbuda',
    name_es: 'Antigua y Barbuda',
    name_de: 'Antigua und Barbuda',
    name_it: 'Antigua e Barbuda',
    telephone_code: 1268,
  },
  {
    iso_alpha2: 'AR',
    iso_alpha3: 'ARG',
    accepted: true,
    card_partner_accepted: false,
    name_fr: 'Argentine',
    name_en: 'Argentina',
    name_es: 'Argentina',
    name_de: 'Argentinien',
    name_it: 'Argentina',
    telephone_code: 54,
  },
  {
    iso_alpha2: 'AM',
    iso_alpha3: 'ARM',
    accepted: true,
    card_partner_accepted: false,
    name_fr: 'Arménie',
    name_en: 'Armenia',
    name_es: 'Armenia',
    name_de: 'Armenien',
    name_it: 'Armenia',
    telephone_code: 374,
  },
  {
    iso_alpha2: 'AW',
    iso_alpha3: 'ABW',
    accepted: true,
    card_partner_accepted: false,
    name_fr: 'Aruba',
    name_en: 'Aruba',
    name_es: 'Aruba',
    name_de: 'Aruba',
    name_it: 'Aruba',
    telephone_code: 297,
  },
  {
    iso_alpha2: 'AU',
    iso_alpha3: 'AUS',
    accepted: true,
    card_partner_accepted: false,
    name_fr: 'Australie',
    name_en: 'Australia',
    name_es: 'Australia',
    name_de: 'Australien',
    name_it: 'Australia',
    telephone_code: 61,
  },
  {
    iso_alpha2: 'AT',
    iso_alpha3: 'AUT',
    accepted: true,
    card_partner_accepted: true,
    name_fr: 'Autriche',
    name_en: 'Austria',
    name_es: 'Austria',
    name_de: 'Österreich',
    name_it: 'Austria',
    telephone_code: 43,
  },
  {
    iso_alpha2: 'AZ',
    iso_alpha3: 'AZE',
    accepted: true,
    card_partner_accepted: false,
    name_fr: 'Azerbaïdjan',
    name_en: 'Azerbaijan',
    name_es: 'Azerbaiyán',
    name_de: 'Aserbaidschan',
    name_it: 'Azerbaijan',
    telephone_code: 994,
  },
  {
    iso_alpha2: 'BS',
    iso_alpha3: 'BHS',
    accepted: false,
    card_partner_accepted: false,
    name_fr: 'Bahamas',
    name_en: 'Bahamas',
    name_es: 'Bahamas',
    name_de: 'Bahamas',
    name_it: 'Bahamas',
    telephone_code: 1242,
  },
  {
    iso_alpha2: 'BH',
    iso_alpha3: 'BHR',
    accepted: true,
    card_partner_accepted: false,
    name_fr: 'Bahreïn',
    name_en: 'Bahrain',
    name_es: 'Baréin',
    name_de: 'Bahrain',
    name_it: 'Bahrein',
    telephone_code: 973,
  },
  {
    iso_alpha2: 'BD',
    iso_alpha3: 'BGD',
    accepted: true,
    card_partner_accepted: false,
    name_fr: 'Bangladesh',
    name_en: 'Bangladesh',
    name_es: 'Bangladés',
    name_de: 'Bangladesch',
    name_it: 'Bangladesh',
    telephone_code: 880,
  },
  {
    iso_alpha2: 'BB',
    iso_alpha3: 'BRB',
    accepted: false,
    card_partner_accepted: false,
    name_fr: 'Barbade',
    name_en: 'Barbados',
    name_es: 'Barbados',
    name_de: 'Barbados',
    name_it: 'Barbados',
    telephone_code: 1246,
  },
  {
    iso_alpha2: 'BY',
    iso_alpha3: 'BLR',
    accepted: true,
    card_partner_accepted: false,
    name_fr: 'Biélorussie',
    name_en: 'Belarus',
    name_es: 'Bielorrusia',
    name_de: 'Weißrussland',
    name_it: 'Bielorussia',
    telephone_code: 375,
  },
  {
    iso_alpha2: 'BE',
    iso_alpha3: 'BEL',
    accepted: true,
    card_partner_accepted: true,
    name_fr: 'Belgique',
    name_en: 'Belgium',
    name_es: 'Bélgica',
    name_de: 'Belgien',
    name_it: 'Belgio',
    telephone_code: 32,
  },
  {
    iso_alpha2: 'BZ',
    iso_alpha3: 'BLZ',
    accepted: true,
    card_partner_accepted: false,
    name_fr: 'Belize',
    name_en: 'Belize',
    name_es: 'Belice',
    name_de: 'Belize',
    name_it: 'Belize',
    telephone_code: 501,
  },
  {
    iso_alpha2: 'BJ',
    iso_alpha3: 'BEN',
    accepted: true,
    card_partner_accepted: false,
    name_fr: 'Bénin',
    name_en: 'Benin',
    name_es: 'Benín',
    name_de: 'Benin',
    name_it: 'Benin',
    telephone_code: 229,
  },
  {
    iso_alpha2: 'BM',
    iso_alpha3: 'BMU',
    accepted: true,
    card_partner_accepted: false,
    name_fr: 'Bermudes',
    name_en: 'Bermuda',
    name_es: 'Bermudas',
    name_de: 'Bermuda',
    name_it: 'Bermuda',
    telephone_code: 1441,
  },
  {
    iso_alpha2: 'BT',
    iso_alpha3: 'BTN',
    accepted: true,
    card_partner_accepted: false,
    name_fr: 'Bhoutan',
    name_en: 'Bhutan',
    name_es: 'Bután',
    name_de: 'Bhutan',
    name_it: 'Bhutan',
    telephone_code: 975,
  },
  {
    iso_alpha2: 'BO',
    iso_alpha3: 'BOL',
    accepted: true,
    card_partner_accepted: false,
    name_fr: 'Bolivie',
    name_en: 'Bolivia',
    name_es: 'Bolivia',
    name_de: 'Plurinationaler Staat Bolivien',
    name_it: 'Bolivia',
    telephone_code: 591,
  },
  {
    iso_alpha2: 'BQ',
    iso_alpha3: 'BES',
    accepted: true,
    card_partner_accepted: false,
    name_fr: 'Saint-Eustache et Saba',
    name_en: 'Bonaire',
    name_es: 'San Eustaquio y Saba',
    name_de: 'Sint Eustatius und Saba',
    name_it: 'Isole BES',
    telephone_code: 0,
  },
  {
    iso_alpha2: 'BA',
    iso_alpha3: 'BIH',
    accepted: false,
    card_partner_accepted: false,
    name_fr: 'Bosnie-Herzégovine',
    name_en: 'Bosnia and Herzegovina',
    name_es: 'Bosnia-Herzegovina',
    name_de: 'Bosnien und Herzegowina',
    name_it: 'Bosnia ed Erzegovina',
    telephone_code: 387,
  },
  {
    iso_alpha2: 'BW',
    iso_alpha3: 'BWA',
    accepted: false,
    card_partner_accepted: false,
    name_fr: 'Botswana',
    name_en: 'Botswana',
    name_es: 'Botsuana',
    name_de: 'Botswana',
    name_it: 'Botswana',
    telephone_code: 267,
  },
  {
    iso_alpha2: 'BV',
    iso_alpha3: 'BVT',
    accepted: true,
    card_partner_accepted: false,
    name_fr: 'Île Bouvet',
    name_en: 'Bouvet Island',
    name_es: 'Isla Bouvet',
    name_de: 'Bouvet-Insel',
    name_it: 'Isola Bouvet',
    telephone_code: null,
  },
  {
    iso_alpha2: 'BR',
    iso_alpha3: 'BRA',
    accepted: true,
    card_partner_accepted: true,
    name_fr: 'Brésil',
    name_en: 'Brazil',
    name_es: 'Brasil',
    name_de: 'Brasilien',
    name_it: 'Brasile',
    telephone_code: 55,
  },
  {
    iso_alpha2: 'IO',
    iso_alpha3: 'IOT',
    accepted: true,
    card_partner_accepted: false,
    name_fr: 'Territoire britannique de locéan Indien',
    name_en: 'British Indian Ocean Territory',
    name_es: 'Territorio Británico del Océano Índico',
    name_de: 'Britisches Territorium im Indischen Ozean',
    name_it: 'Territori Britannici dellOceano Indiano',
    telephone_code: null,
  },
  {
    iso_alpha2: 'BN',
    iso_alpha3: 'BRN',
    accepted: true,
    card_partner_accepted: false,
    name_fr: 'Brunei',
    name_en: 'Brunei Darussalam',
    name_es: 'Brunéi',
    name_de: 'Brunei Darussalam',
    name_it: 'Brunei',
    telephone_code: 673,
  },
  {
    iso_alpha2: 'BG',
    iso_alpha3: 'BGR',
    accepted: true,
    card_partner_accepted: true,
    name_fr: 'Bulgarie',
    name_en: 'Bulgaria',
    name_es: 'Bulgaria',
    name_de: 'Bulgarien',
    name_it: 'Bulgaria',
    telephone_code: 359,
  },
  {
    iso_alpha2: 'BF',
    iso_alpha3: 'BFA',
    accepted: false,
    card_partner_accepted: false,
    name_fr: 'Burkina Faso',
    name_en: 'Burkina Faso',
    name_es: 'Burkina Faso',
    name_de: 'Burkina Faso',
    name_it: 'Burkina Faso',
    telephone_code: 226,
  },
  {
    iso_alpha2: 'BI',
    iso_alpha3: 'BDI',
    accepted: true,
    card_partner_accepted: false,
    name_fr: 'Burundi',
    name_en: 'Burundi',
    name_es: 'Burundi',
    name_de: 'Burundi',
    name_it: 'Burundi',
    telephone_code: 257,
  },
  {
    iso_alpha2: 'KH',
    iso_alpha3: 'KHM',
    accepted: false,
    card_partner_accepted: false,
    name_fr: 'Cambodge',
    name_en: 'Cambodia',
    name_es: 'Camboya',
    name_de: 'Kambodscha',
    name_it: 'Cambogia',
    telephone_code: 855,
  },
  {
    iso_alpha2: 'CM',
    iso_alpha3: 'CMR',
    accepted: true,
    card_partner_accepted: false,
    name_fr: 'Cameroun',
    name_en: 'Cameroon',
    name_es: 'Camerún',
    name_de: 'Kamerun',
    name_it: 'Camerun',
    telephone_code: 237,
  },
  {
    iso_alpha2: 'CA',
    iso_alpha3: 'CAN',
    accepted: true,
    card_partner_accepted: true,
    name_fr: 'Canada',
    name_en: 'Canada',
    name_es: 'Canadá',
    name_de: 'Kanada',
    name_it: 'Canada',
    telephone_code: 1,
  },
  {
    iso_alpha2: 'CV',
    iso_alpha3: 'CPV',
    accepted: true,
    card_partner_accepted: false,
    name_fr: 'Cap-Vert',
    name_en: 'Cape Verde',
    name_es: 'Cabo Verde',
    name_de: 'Kap Verde',
    name_it: 'Cabo Verde',
    telephone_code: 238,
  },
  {
    iso_alpha2: 'KY',
    iso_alpha3: 'CYM',
    accepted: false,
    card_partner_accepted: false,
    name_fr: 'Îles Caïmans',
    name_en: 'Cayman Islands',
    name_es: 'Islas Caimán',
    name_de: 'Kaimaninseln',
    name_it: 'Isole Cayman',
    telephone_code: 1345,
  },
  {
    iso_alpha2: 'CF',
    iso_alpha3: 'CAF',
    accepted: true,
    card_partner_accepted: false,
    name_fr: 'République centrafricaine',
    name_en: 'Central African Republic',
    name_es: 'República Centroafricana',
    name_de: 'Zentralafrikanische Republik',
    name_it: 'Centrafrica',
    telephone_code: 236,
  },
  {
    iso_alpha2: 'TD',
    iso_alpha3: 'TCD',
    accepted: true,
    card_partner_accepted: false,
    name_fr: 'Tchad',
    name_en: 'Chad',
    name_es: 'Chad',
    name_de: 'Tschad',
    name_it: 'Ciad',
    telephone_code: 235,
  },
  {
    iso_alpha2: 'CL',
    iso_alpha3: 'CHL',
    accepted: true,
    card_partner_accepted: true,
    name_fr: 'Chili',
    name_en: 'Chile',
    name_es: 'Chile',
    name_de: 'Chile',
    name_it: 'Chile',
    telephone_code: 56,
  },
  {
    iso_alpha2: 'CN',
    iso_alpha3: 'CHN',
    accepted: true,
    card_partner_accepted: false,
    name_fr: 'Chine',
    name_en: 'China',
    name_es: 'China',
    name_de: 'China',
    name_it: 'Cina',
    telephone_code: 86,
  },
  {
    iso_alpha2: 'CX',
    iso_alpha3: 'CXR',
    accepted: true,
    card_partner_accepted: false,
    name_fr: 'Île Christmas',
    name_en: 'Christmas Island',
    name_es: 'Isla de Navidad',
    name_de: 'Weihnachtsinsel',
    name_it: 'Isola Christmas',
    telephone_code: 61,
  },
  {
    iso_alpha2: 'CC',
    iso_alpha3: 'CCK',
    accepted: true,
    card_partner_accepted: false,
    name_fr: 'Îles Cocos',
    name_en: 'Cocos (Keeling) Islands',
    name_es: 'Islas Cocos',
    name_de: 'Kokosinseln',
    name_it: 'Isole Cocos',
    telephone_code: 61,
  },
  {
    iso_alpha2: 'CO',
    iso_alpha3: 'COL',
    accepted: true,
    card_partner_accepted: false,
    name_fr: 'Colombie',
    name_en: 'Colombia',
    name_es: 'Colombia',
    name_de: 'Kolumbien',
    name_it: 'Colombia',
    telephone_code: 57,
  },
  {
    iso_alpha2: 'KM',
    iso_alpha3: 'COM',
    accepted: true,
    card_partner_accepted: false,
    name_fr: 'Comores',
    name_en: 'Comoros',
    name_es: 'Comoras',
    name_de: 'Komoren',
    name_it: 'Comore',
    telephone_code: 269,
  },
  {
    iso_alpha2: 'CG',
    iso_alpha3: 'COG',
    accepted: true,
    card_partner_accepted: false,
    name_fr: 'République du Congo',
    name_en: 'Congo',
    name_es: 'República del Congo',
    name_de: 'Republik Kongo',
    name_it: 'Congo rep',
    telephone_code: 242,
  },
  {
    iso_alpha2: 'CD',
    iso_alpha3: 'COD',
    accepted: true,
    card_partner_accepted: false,
    name_fr: 'République démocratique du Congo',
    name_en: 'Democratic republic of Congo',
    name_es: 'República Democrática del Congo',
    name_de: 'Demokratische Republik Kongo',
    name_it: 'Congo r.d.',
    telephone_code: 243,
  },
  {
    iso_alpha2: 'CK',
    iso_alpha3: 'COK',
    accepted: true,
    card_partner_accepted: false,
    name_fr: 'Îles Cook',
    name_en: 'Cook Islands',
    name_es: 'Islas Cook',
    name_de: 'Cookinseln',
    name_it: 'Isole Cook',
    telephone_code: 682,
  },
  {
    iso_alpha2: 'CR',
    iso_alpha3: 'CRI',
    accepted: true,
    card_partner_accepted: false,
    name_fr: 'Costa Rica',
    name_en: 'Costa Rica',
    name_es: 'Costa Rica',
    name_de: 'Costa Rica',
    name_it: 'Costarica',
    telephone_code: 506,
  },
  {
    iso_alpha2: 'CI',
    iso_alpha3: 'CIV',
    accepted: true,
    card_partner_accepted: false,
    name_fr: 'Côte dIvoire',
    name_en: 'Côte dIvoire',
    name_es: 'Costa de Marfil',
    name_de: 'Elfenbeinküste',
    name_it: 'Costa dAvorio',
    telephone_code: 225,
  },
  {
    iso_alpha2: 'HR',
    iso_alpha3: 'HRV',
    accepted: true,
    card_partner_accepted: true,
    name_fr: 'Croatie',
    name_en: 'Croatia',
    name_es: 'Croacia',
    name_de: 'Kroatien',
    name_it: 'Croazia',
    telephone_code: 385,
  },
  {
    iso_alpha2: 'CU',
    iso_alpha3: 'CUB',
    accepted: true,
    card_partner_accepted: false,
    name_fr: 'Cuba',
    name_en: 'Cuba',
    name_es: 'Cuba',
    name_de: 'Kuba',
    name_it: 'Cuba',
    telephone_code: 53,
  },
  {
    iso_alpha2: 'CW',
    iso_alpha3: 'CUW',
    accepted: true,
    card_partner_accepted: false,
    name_fr: 'Curaçao',
    name_en: 'Curaçao',
    name_es: 'Curazao',
    name_de: 'Curaçao',
    name_it: 'Curaçao',
    telephone_code: null,
  },
  {
    iso_alpha2: 'CY',
    iso_alpha3: 'CYP',
    accepted: true,
    card_partner_accepted: true,
    name_fr: 'Chypre',
    name_en: 'Cyprus',
    name_es: 'Chipre',
    name_de: 'Zypern',
    name_it: 'Cipro',
    telephone_code: 357,
  },
  {
    iso_alpha2: 'CZ',
    iso_alpha3: 'CZE',
    accepted: true,
    card_partner_accepted: true,
    name_fr: 'République tchèque',
    name_en: 'Czech Republic',
    name_es: 'Chequia',
    name_de: 'Tschechien',
    name_it: 'Repubblica Ceca',
    telephone_code: 420,
  },
  {
    iso_alpha2: 'DK',
    iso_alpha3: 'DNK',
    accepted: true,
    card_partner_accepted: true,
    name_fr: 'Danemark',
    name_en: 'Denmark',
    name_es: 'Dinamarca',
    name_de: 'Dänemark',
    name_it: 'Danimarca',
    telephone_code: 45,
  },
  {
    iso_alpha2: 'DJ',
    iso_alpha3: 'DJI',
    accepted: true,
    card_partner_accepted: false,
    name_fr: 'Djibouti',
    name_en: 'Djibouti',
    name_es: 'Yibuti',
    name_de: 'Dschibouti',
    name_it: 'Gibuti',
    telephone_code: 253,
  },
  {
    iso_alpha2: 'DM',
    iso_alpha3: 'DMA',
    accepted: false,
    card_partner_accepted: false,
    name_fr: 'Dominique',
    name_en: 'Dominica',
    name_es: 'Dominica',
    name_de: 'Dominica',
    name_it: 'Dominica',
    telephone_code: 1767,
  },
  {
    iso_alpha2: 'DO',
    iso_alpha3: 'DOM',
    accepted: true,
    card_partner_accepted: false,
    name_fr: 'République dominicaine',
    name_en: 'Dominican Republic',
    name_es: 'República Dominicana',
    name_de: 'Dominikanische Republik',
    name_it: 'Dominicana rep.',
    telephone_code: 1809,
  },
  {
    iso_alpha2: 'EC',
    iso_alpha3: 'ECU',
    accepted: true,
    card_partner_accepted: false,
    name_fr: 'Équateur',
    name_en: 'Ecuador',
    name_es: 'Ecuador',
    name_de: 'Ekuador',
    name_it: 'Ecuador',
    telephone_code: 593,
  },
  {
    iso_alpha2: 'EG',
    iso_alpha3: 'EGY',
    accepted: true,
    card_partner_accepted: false,
    name_fr: 'Égypte',
    name_en: 'Egypt',
    name_es: 'Egipto',
    name_de: 'Ägypten',
    name_it: 'Egitto',
    telephone_code: 20,
  },
  {
    iso_alpha2: 'SV',
    iso_alpha3: 'SLV',
    accepted: true,
    card_partner_accepted: false,
    name_fr: 'Salvador',
    name_en: 'El Salvador',
    name_es: 'El Salvador',
    name_de: 'El Salvador',
    name_it: 'El Salvador',
    telephone_code: 503,
  },
  {
    iso_alpha2: 'GQ',
    iso_alpha3: 'GNQ',
    accepted: true,
    card_partner_accepted: false,
    name_fr: 'Guinée équatoriale',
    name_en: 'Equatorial Guinea',
    name_es: 'Guinea Ecuatorial',
    name_de: 'Äquatorialguinea',
    name_it: 'Guinea Equatoriale',
    telephone_code: 240,
  },
  {
    iso_alpha2: 'ER',
    iso_alpha3: 'ERI',
    accepted: true,
    card_partner_accepted: false,
    name_fr: 'Érythrée',
    name_en: 'Eritrea',
    name_es: 'Eritrea',
    name_de: 'Eritrea',
    name_it: 'Eritrea',
    telephone_code: 291,
  },
  {
    iso_alpha2: 'EE',
    iso_alpha3: 'EST',
    accepted: true,
    card_partner_accepted: true,
    name_fr: 'Estonie',
    name_en: 'Estonia',
    name_es: 'Estonia',
    name_de: 'Estland',
    name_it: 'Estonia',
    telephone_code: 372,
  },
  {
    iso_alpha2: 'ET',
    iso_alpha3: 'ETH',
    accepted: false,
    card_partner_accepted: false,
    name_fr: 'Éthiopie',
    name_en: 'Ethiopia',
    name_es: 'Etiopía',
    name_de: 'Äthiopien',
    name_it: 'Etiopia',
    telephone_code: 251,
  },
  {
    iso_alpha2: 'FK',
    iso_alpha3: 'FLK',
    accepted: true,
    card_partner_accepted: false,
    name_fr: 'Îles Malouines',
    name_en: 'Falkland Islands (Malvinas)',
    name_es: 'Islas Malvinas',
    name_de: 'Falklandinseln',
    name_it: 'Isole Falkland',
    telephone_code: 500,
  },
  {
    iso_alpha2: 'FO',
    iso_alpha3: 'FRO',
    accepted: true,
    card_partner_accepted: false,
    name_fr: 'Îles Féroé',
    name_en: 'Faroe Islands',
    name_es: 'Islas Feroe',
    name_de: 'Faröer',
    name_it: 'Isole Faroe',
    telephone_code: 298,
  },
  {
    iso_alpha2: 'FJ',
    iso_alpha3: 'FJI',
    accepted: false,
    card_partner_accepted: false,
    name_fr: 'Fidji',
    name_en: 'Fiji',
    name_es: 'Fiyi',
    name_de: 'Fidschi',
    name_it: 'Isole Fiji',
    telephone_code: 679,
  },
  {
    iso_alpha2: 'FI',
    iso_alpha3: 'FIN',
    accepted: true,
    card_partner_accepted: true,
    name_fr: 'Finlande',
    name_en: 'Finland',
    name_es: 'Finlandia',
    name_de: 'Finnland',
    name_it: 'Finlandia',
    telephone_code: 358,
  },
  {
    iso_alpha2: 'FR',
    iso_alpha3: 'FRA',
    accepted: true,
    card_partner_accepted: true,
    name_fr: 'France',
    name_en: 'France',
    name_es: 'Francia',
    name_de: 'Frankreich',
    name_it: 'Francia',
    telephone_code: 33,
  },
  {
    iso_alpha2: 'GF',
    iso_alpha3: 'GUF',
    accepted: true,
    card_partner_accepted: true,
    name_fr: 'Guyane',
    name_en: 'French Guiana',
    name_es: 'Guayana Francesa',
    name_de: 'Französisch-Guayana',
    name_it: 'Guyana Francese',
    telephone_code: null,
  },
  {
    iso_alpha2: 'PF',
    iso_alpha3: 'PYF',
    accepted: true,
    card_partner_accepted: true,
    name_fr: 'Polynésie française',
    name_en: 'French Polynesia',
    name_es: 'Polinesia Francesa',
    name_de: 'Französisch-Polynesien',
    name_it: 'Polinesia Francese',
    telephone_code: 689,
  },
  {
    iso_alpha2: 'TF',
    iso_alpha3: 'ATF',
    accepted: true,
    card_partner_accepted: false,
    name_fr: 'Terres australes et antarctiques françaises',
    name_en: 'French Southern Territories',
    name_es: 'Tierras Australes y Antárticas Francesas',
    name_de: 'Französische Süd- und Antarktisgebiete',
    name_it: 'Terre australi e antartiche francesi',
    telephone_code: null,
  },
  {
    iso_alpha2: 'GA',
    iso_alpha3: 'GAB',
    accepted: true,
    card_partner_accepted: false,
    name_fr: 'Gabon',
    name_en: 'Gabon',
    name_es: 'Gabón',
    name_de: 'Gabun',
    name_it: 'Gabon',
    telephone_code: 241,
  },
  {
    iso_alpha2: 'GM',
    iso_alpha3: 'GMB',
    accepted: true,
    card_partner_accepted: false,
    name_fr: 'Gambie',
    name_en: 'Gambia',
    name_es: 'Gambia',
    name_de: 'Gambia',
    name_it: 'Gambia',
    telephone_code: 220,
  },
  {
    iso_alpha2: 'GE',
    iso_alpha3: 'GEO',
    accepted: true,
    card_partner_accepted: false,
    name_fr: 'Géorgie',
    name_en: 'Georgia',
    name_es: 'Georgia',
    name_de: 'Georgien',
    name_it: 'Georgia',
    telephone_code: 995,
  },
  {
    iso_alpha2: 'DE',
    iso_alpha3: 'DEU',
    accepted: false,
    card_partner_accepted: false,
    name_fr: 'Allemagne',
    name_en: 'Germany',
    name_es: 'Alemania',
    name_de: 'Deutschland',
    name_it: 'Germania',
    telephone_code: 49,
  },
  {
    iso_alpha2: 'GH',
    iso_alpha3: 'GHA',
    accepted: false,
    card_partner_accepted: false,
    name_fr: 'Ghana',
    name_en: 'Ghana',
    name_es: 'Ghana',
    name_de: 'Ghana',
    name_it: 'Ghana',
    telephone_code: 233,
  },
  {
    iso_alpha2: 'GI',
    iso_alpha3: 'GIB',
    accepted: true,
    card_partner_accepted: false,
    name_fr: 'Gibraltar',
    name_en: 'Gibraltar',
    name_es: 'Gibraltar',
    name_de: 'Gibraltar',
    name_it: 'Gibilterra',
    telephone_code: 350,
  },
  {
    iso_alpha2: 'GR',
    iso_alpha3: 'GRC',
    accepted: true,
    card_partner_accepted: true,
    name_fr: 'Grèce',
    name_en: 'Greece',
    name_es: 'Grecia',
    name_de: 'Griechenland',
    name_it: 'Grecia',
    telephone_code: 30,
  },
  {
    iso_alpha2: 'GL',
    iso_alpha3: 'GRL',
    accepted: true,
    card_partner_accepted: false,
    name_fr: 'Groenland',
    name_en: 'Greenland',
    name_es: 'Groenlandia',
    name_de: 'Grönland',
    name_it: 'Groenlandia',
    telephone_code: 299,
  },
  {
    iso_alpha2: 'GD',
    iso_alpha3: 'GRD',
    accepted: true,
    card_partner_accepted: false,
    name_fr: 'Grenade',
    name_en: 'Grenada',
    name_es: 'Granada',
    name_de: 'Grenada',
    name_it: 'Grenada',
    telephone_code: 1473,
  },
  {
    iso_alpha2: 'GP',
    iso_alpha3: 'GLP',
    accepted: true,
    card_partner_accepted: true,
    name_fr: 'Guadeloupe',
    name_en: 'Guadeloupe',
    name_es: 'Guadalupe',
    name_de: 'Guadeloupe',
    name_it: 'Guadalupa',
    telephone_code: null,
  },
  {
    iso_alpha2: 'GU',
    iso_alpha3: 'GUM',
    accepted: false,
    card_partner_accepted: false,
    name_fr: 'Guam',
    name_en: 'Guam',
    name_es: 'Guam',
    name_de: 'Guam',
    name_it: 'Guam',
    telephone_code: 1671,
  },
  {
    iso_alpha2: 'GT',
    iso_alpha3: 'GTM',
    accepted: true,
    card_partner_accepted: false,
    name_fr: 'Guatemala',
    name_en: 'Guatemala',
    name_es: 'Guatemala',
    name_de: 'Guatemala',
    name_it: 'Guatemala',
    telephone_code: 502,
  },
  {
    iso_alpha2: 'GG',
    iso_alpha3: 'GGY',
    accepted: true,
    card_partner_accepted: false,
    name_fr: 'Guernesey',
    name_en: 'Guernsey',
    name_es: 'Guernsey',
    name_de: 'Guernsey',
    name_it: 'Guernsey',
    telephone_code: null,
  },
  {
    iso_alpha2: 'GN',
    iso_alpha3: 'GIN',
    accepted: true,
    card_partner_accepted: false,
    name_fr: 'Guinée',
    name_en: 'Guinea',
    name_es: 'Guinea',
    name_de: 'Guinea',
    name_it: 'Guinea',
    telephone_code: 224,
  },
  {
    iso_alpha2: 'GW',
    iso_alpha3: 'GNB',
    accepted: true,
    card_partner_accepted: false,
    name_fr: 'Guinée-Bissau',
    name_en: 'Guinea-Bissau',
    name_es: 'Guinea-Bisáu',
    name_de: 'Guinea-Bissau',
    name_it: 'Guinea Bissau',
    telephone_code: 245,
  },
  {
    iso_alpha2: 'GY',
    iso_alpha3: 'GUY',
    accepted: false,
    card_partner_accepted: false,
    name_fr: 'Guyana',
    name_en: 'Guyana',
    name_es: 'Guyana',
    name_de: 'Guyana',
    name_it: 'Guyana',
    telephone_code: 592,
  },
  {
    iso_alpha2: 'HT',
    iso_alpha3: 'HTI',
    accepted: true,
    card_partner_accepted: false,
    name_fr: 'Haïti',
    name_en: 'Haiti',
    name_es: 'Haití',
    name_de: 'Haiti',
    name_it: 'Haïti',
    telephone_code: 509,
  },
  {
    iso_alpha2: 'HM',
    iso_alpha3: 'HMD',
    accepted: true,
    card_partner_accepted: false,
    name_fr: 'Îles Heard-et-MacDonald',
    name_en: 'Heard Island and McDonald Islands',
    name_es: 'Islas Heard y McDonald',
    name_de: 'Heard und McDonaldinseln',
    name_it: 'Isole Heard e McDonald',
    telephone_code: null,
  },
  {
    iso_alpha2: 'VA',
    iso_alpha3: 'VAT',
    accepted: true,
    card_partner_accepted: false,
    name_fr: 'Saint-Siège (État de la Cité du Vatican)',
    name_en: 'Holy See (Vatican City State)',
    name_es: 'Ciudad del Vaticano',
    name_de: 'Vatikan (Vatikanstadt)',
    name_it: ' Vaticano',
    telephone_code: 39,
  },
  {
    iso_alpha2: 'HN',
    iso_alpha3: 'HND',
    accepted: true,
    card_partner_accepted: false,
    name_fr: 'Honduras',
    name_en: 'Honduras',
    name_es: 'Honduras',
    name_de: 'Honduras',
    name_it: 'Honduras',
    telephone_code: 504,
  },
  {
    iso_alpha2: 'HK',
    iso_alpha3: 'HKG',
    accepted: true,
    card_partner_accepted: true,
    name_fr: 'Hong Kong',
    name_en: 'Hong Kong',
    name_es: 'Hong Kong',
    name_de: 'Hongkong',
    name_it: 'Hong Kong',
    telephone_code: 852,
  },
  {
    iso_alpha2: 'HU',
    iso_alpha3: 'HUN',
    accepted: true,
    card_partner_accepted: true,
    name_fr: 'Hongrie',
    name_en: 'Hungary',
    name_es: 'Hungría',
    name_de: 'Ungarn',
    name_it: 'Ungheria',
    telephone_code: 36,
  },
  {
    iso_alpha2: 'IS',
    iso_alpha3: 'ISL',
    accepted: true,
    card_partner_accepted: true,
    name_fr: 'Islande',
    name_en: 'Iceland',
    name_es: 'Islandia',
    name_de: 'Island',
    name_it: 'Islanda',
    telephone_code: 354,
  },
  {
    iso_alpha2: 'IN',
    iso_alpha3: 'IND',
    accepted: true,
    card_partner_accepted: true,
    name_fr: 'Inde',
    name_en: 'India',
    name_es: 'India',
    name_de: 'Indien',
    name_it: 'India',
    telephone_code: 91,
  },
  {
    iso_alpha2: 'ID',
    iso_alpha3: 'IDN',
    accepted: true,
    card_partner_accepted: false,
    name_fr: 'Indonésie',
    name_en: 'Indonesia',
    name_es: 'Indonesia',
    name_de: 'Indonesien',
    name_it: 'Indonesia',
    telephone_code: 62,
  },
  {
    iso_alpha2: 'IR',
    iso_alpha3: 'IRN',
    accepted: false,
    card_partner_accepted: false,
    name_fr: 'Iran',
    name_en: 'Iran',
    name_es: 'Irán',
    name_de: 'Islamische Republik Iran',
    name_it: 'Iran',
    telephone_code: 98,
  },
  {
    iso_alpha2: 'IQ',
    iso_alpha3: 'IRQ',
    accepted: false,
    card_partner_accepted: false,
    name_fr: 'Irak',
    name_en: 'Iraq',
    name_es: 'Irak',
    name_de: 'Irak',
    name_it: 'Iraq',
    telephone_code: 964,
  },
  {
    iso_alpha2: 'IE',
    iso_alpha3: 'IRL',
    accepted: true,
    card_partner_accepted: true,
    name_fr: 'Irlande',
    name_en: 'Ireland',
    name_es: 'Irlanda',
    name_de: 'Irland',
    name_it: 'Irlanda',
    telephone_code: 353,
  },
  {
    iso_alpha2: 'IM',
    iso_alpha3: 'IMN',
    accepted: true,
    card_partner_accepted: false,
    name_fr: 'Île de Man',
    name_en: 'Isle of Man',
    name_es: 'Isla de Man',
    name_de: 'Isle of Man',
    name_it: 'Isola di Man',
    telephone_code: 44,
  },
  {
    iso_alpha2: 'IL',
    iso_alpha3: 'ISR',
    accepted: true,
    card_partner_accepted: false,
    name_fr: 'Israël',
    name_en: 'Israel',
    name_es: 'Israel',
    name_de: 'Israel',
    name_it: 'Israele',
    telephone_code: 972,
  },
  {
    iso_alpha2: 'IT',
    iso_alpha3: 'ITA',
    accepted: true,
    card_partner_accepted: true,
    name_fr: 'Italie',
    name_en: 'Italy',
    name_es: 'Italia',
    name_de: 'Italien',
    name_it: 'Italia',
    telephone_code: 39,
  },
  {
    iso_alpha2: 'JM',
    iso_alpha3: 'JAM',
    accepted: false,
    card_partner_accepted: false,
    name_fr: 'Jamaïque',
    name_en: 'Jamaica',
    name_es: 'Jamaica',
    name_de: 'Jamaika',
    name_it: 'Giamaica',
    telephone_code: 1876,
  },
  {
    iso_alpha2: 'JP',
    iso_alpha3: 'JPN',
    accepted: true,
    card_partner_accepted: true,
    name_fr: 'Japon',
    name_en: 'Japan',
    name_es: 'Japón',
    name_de: 'Japan',
    name_it: 'Giappone',
    telephone_code: 81,
  },
  {
    iso_alpha2: 'JE',
    iso_alpha3: 'JEY',
    accepted: true,
    card_partner_accepted: false,
    name_fr: 'Jersey',
    name_en: 'Jersey',
    name_es: 'Jersey',
    name_de: 'Jersey',
    name_it: 'Jersey',
    telephone_code: null,
  },
  {
    iso_alpha2: 'JO',
    iso_alpha3: 'JOR',
    accepted: true,
    card_partner_accepted: false,
    name_fr: 'Jordanie',
    name_en: 'Jordan',
    name_es: 'Jordania',
    name_de: 'Jordanien',
    name_it: 'Giordania',
    telephone_code: 962,
  },
  {
    iso_alpha2: 'KZ',
    iso_alpha3: 'KAZ',
    accepted: true,
    card_partner_accepted: false,
    name_fr: 'Kazakhstan',
    name_en: 'Kazakhstan',
    name_es: 'Kazajistán',
    name_de: 'Kasachstan',
    name_it: 'Kazakhstan',
    telephone_code: 7,
  },
  {
    iso_alpha2: 'KE',
    iso_alpha3: 'KEN',
    accepted: true,
    card_partner_accepted: false,
    name_fr: 'Kenya',
    name_en: 'Kenya',
    name_es: 'Kenia',
    name_de: 'Kenia',
    name_it: 'Kenya',
    telephone_code: 254,
  },
  {
    iso_alpha2: 'KI',
    iso_alpha3: 'KIR',
    accepted: true,
    card_partner_accepted: false,
    name_fr: 'Kiribati',
    name_en: 'Kiribati',
    name_es: 'Kiribati',
    name_de: 'Kiribati',
    name_it: 'Kiribati',
    telephone_code: 686,
  },
  {
    iso_alpha2: 'KP',
    iso_alpha3: 'PRK',
    accepted: false,
    card_partner_accepted: false,
    name_fr: 'Corée du Nord',
    name_en: 'Korea (North)',
    name_es: 'Corea del Norte',
    name_de: 'Demokratische Volksrepublik Korea',
    name_it: 'Corea r.d.p.',
    telephone_code: 850,
  },
  {
    iso_alpha2: 'KR',
    iso_alpha3: 'KOR',
    accepted: true,
    card_partner_accepted: true,
    name_fr: 'Corée du Sud',
    name_en: 'Korea (South)',
    name_es: 'Corea del Sur',
    name_de: 'Republik Korea',
    name_it: 'Corea rep.',
    telephone_code: 82,
  },
  {
    iso_alpha2: 'KW',
    iso_alpha3: 'KWT',
    accepted: true,
    card_partner_accepted: false,
    name_fr: 'Koweït',
    name_en: 'Kuwait',
    name_es: 'Kuwait',
    name_de: 'Kuwait',
    name_it: 'Kuwait',
    telephone_code: 965,
  },
  {
    iso_alpha2: 'KG',
    iso_alpha3: 'KGZ',
    accepted: true,
    card_partner_accepted: false,
    name_fr: 'Kirghizistan',
    name_en: 'Kyrgyzstan',
    name_es: 'Kirguistán',
    name_de: 'Kirgisistan',
    name_it: 'Kyrghizistan',
    telephone_code: 996,
  },
  {
    iso_alpha2: 'LA',
    iso_alpha3: 'LAO',
    accepted: false,
    card_partner_accepted: false,
    name_fr: 'Laos',
    name_en: 'Lao People Democratic Republic',
    name_es: 'Laos',
    name_de: 'Demokratische Volksrepublik Laos',
    name_it: 'Laos',
    telephone_code: 856,
  },
  {
    iso_alpha2: 'LV',
    iso_alpha3: 'LVA',
    accepted: true,
    card_partner_accepted: true,
    name_fr: 'Lettonie',
    name_en: 'Latvia',
    name_es: 'Letonia',
    name_de: 'Lettland',
    name_it: 'Lettonia',
    telephone_code: 371,
  },
  {
    iso_alpha2: 'LB',
    iso_alpha3: 'LBN',
    accepted: true,
    card_partner_accepted: false,
    name_fr: 'Liban',
    name_en: 'Lebanon',
    name_es: 'Líbano',
    name_de: 'Libanon',
    name_it: 'Libano',
    telephone_code: 961,
  },
  {
    iso_alpha2: 'LS',
    iso_alpha3: 'LSO',
    accepted: true,
    card_partner_accepted: false,
    name_fr: 'Lesotho',
    name_en: 'Lesotho',
    name_es: 'Lesoto',
    name_de: 'Lesotho',
    name_it: 'Lesotho',
    telephone_code: 266,
  },
  {
    iso_alpha2: 'LR',
    iso_alpha3: 'LBR',
    accepted: true,
    card_partner_accepted: false,
    name_fr: 'Liberia',
    name_en: 'Liberia',
    name_es: 'Liberia',
    name_de: 'Liberia',
    name_it: 'Liberia',
    telephone_code: 231,
  },
  {
    iso_alpha2: 'LY',
    iso_alpha3: 'LBY',
    accepted: false,
    card_partner_accepted: false,
    name_fr: 'Libye',
    name_en: 'Libya',
    name_es: 'Libia',
    name_de: 'Libyen',
    name_it: 'Libia',
    telephone_code: 218,
  },
  {
    iso_alpha2: 'LI',
    iso_alpha3: 'LIE',
    accepted: true,
    card_partner_accepted: true,
    name_fr: 'Liechtenstein',
    name_en: 'Liechtenstein',
    name_es: 'Liechtenstein',
    name_de: 'Liechtenstein',
    name_it: 'Liechtenstein',
    telephone_code: 423,
  },
  {
    iso_alpha2: 'LT',
    iso_alpha3: 'LTU',
    accepted: true,
    card_partner_accepted: true,
    name_fr: 'Lituanie',
    name_en: 'Lithuania',
    name_es: 'Lituania',
    name_de: 'Litauen',
    name_it: 'Lituania',
    telephone_code: 370,
  },
  {
    iso_alpha2: 'LU',
    iso_alpha3: 'LUX',
    accepted: true,
    card_partner_accepted: true,
    name_fr: 'Luxembourg',
    name_en: 'Luxembourg',
    name_es: 'Luxemburgo',
    name_de: 'Luxemburg',
    name_it: 'Lussemburgo',
    telephone_code: 352,
  },
  {
    iso_alpha2: 'MO',
    iso_alpha3: 'MAC',
    accepted: true,
    card_partner_accepted: false,
    name_fr: 'Macao',
    name_en: 'Macao',
    name_es: 'Macao',
    name_de: 'Macau',
    name_it: 'Macao',
    telephone_code: 853,
  },
  {
    iso_alpha2: 'MK',
    iso_alpha3: 'MKD',
    accepted: true,
    card_partner_accepted: false,
    name_fr: 'Macédoine',
    name_en: 'Macedonia',
    name_es: 'Macedonia',
    name_de: 'Mazedonien',
    name_it: 'Macedonia',
    telephone_code: 389,
  },
  {
    iso_alpha2: 'MG',
    iso_alpha3: 'MDG',
    accepted: true,
    card_partner_accepted: false,
    name_fr: 'Madagascar',
    name_en: 'Madagascar',
    name_es: 'Madagascar',
    name_de: 'Madagaskar',
    name_it: 'Madagascar',
    telephone_code: 261,
  },
  {
    iso_alpha2: 'MW',
    iso_alpha3: 'MWI',
    accepted: true,
    card_partner_accepted: false,
    name_fr: 'Malawi',
    name_en: 'Malawi',
    name_es: 'Malaui',
    name_de: 'Malawi',
    name_it: 'Malawi',
    telephone_code: 265,
  },
  {
    iso_alpha2: 'MY',
    iso_alpha3: 'MYS',
    accepted: true,
    card_partner_accepted: false,
    name_fr: 'Malaisie',
    name_en: 'Malaysia',
    name_es: 'Malasia',
    name_de: 'Malaysia',
    name_it: 'Malaisia',
    telephone_code: 60,
  },
  {
    iso_alpha2: 'MV',
    iso_alpha3: 'MDV',
    accepted: true,
    card_partner_accepted: false,
    name_fr: 'Maldives',
    name_en: 'Maldives',
    name_es: 'Maldivas',
    name_de: 'Malediven',
    name_it: 'Maldive',
    telephone_code: 960,
  },
  {
    iso_alpha2: 'ML',
    iso_alpha3: 'MLI',
    accepted: true,
    card_partner_accepted: false,
    name_fr: 'Mali',
    name_en: 'Mali',
    name_es: 'Mali',
    name_de: 'Mali',
    name_it: 'Mali',
    telephone_code: 223,
  },
  {
    iso_alpha2: 'MT',
    iso_alpha3: 'MLT',
    accepted: true,
    card_partner_accepted: true,
    name_fr: 'Malte',
    name_en: 'Malta',
    name_es: 'Malta',
    name_de: 'Malta',
    name_it: 'Malta',
    telephone_code: 356,
  },
  {
    iso_alpha2: 'MH',
    iso_alpha3: 'MHL',
    accepted: true,
    card_partner_accepted: false,
    name_fr: 'Marshall',
    name_en: 'Marshall Islands',
    name_es: 'Islas Marshall',
    name_de: 'Marshallinseln',
    name_it: 'Isole Marshall',
    telephone_code: 692,
  },
  {
    iso_alpha2: 'MQ',
    iso_alpha3: 'MTQ',
    accepted: true,
    card_partner_accepted: true,
    name_fr: 'Martinique',
    name_en: 'Martinique',
    name_es: 'Martinica',
    name_de: 'Martinique',
    name_it: 'Martinica',
    telephone_code: null,
  },
  {
    iso_alpha2: 'MR',
    iso_alpha3: 'MRT',
    accepted: true,
    card_partner_accepted: false,
    name_fr: 'Mauritanie',
    name_en: 'Mauritania',
    name_es: 'Mauritania',
    name_de: 'Mauretanien',
    name_it: 'Mauritania',
    telephone_code: 222,
  },
  {
    iso_alpha2: 'MU',
    iso_alpha3: 'MUS',
    accepted: false,
    card_partner_accepted: false,
    name_fr: 'Maurice',
    name_en: 'Mauritius',
    name_es: 'Mauricio',
    name_de: 'Mauritius',
    name_it: 'Mauritius',
    telephone_code: 230,
  },
  {
    iso_alpha2: 'YT',
    iso_alpha3: 'MYT',
    accepted: true,
    card_partner_accepted: true,
    name_fr: 'Mayotte',
    name_en: 'Mayotte',
    name_es: 'Mayotte',
    name_de: 'Mayotte',
    name_it: 'Mayotte',
    telephone_code: 262,
  },
  {
    iso_alpha2: 'MX',
    iso_alpha3: 'MEX',
    accepted: true,
    card_partner_accepted: true,
    name_fr: 'Mexique',
    name_en: 'Mexico',
    name_es: 'México',
    name_de: 'Mexiko',
    name_it: 'Messico',
    telephone_code: 52,
  },
  {
    iso_alpha2: 'FM',
    iso_alpha3: 'FSM',
    accepted: true,
    card_partner_accepted: false,
    name_fr: 'Micronésie',
    name_en: 'Micronesia',
    name_es: 'Micronesia',
    name_de: 'Mikronesien',
    name_it: 'Micronesia',
    telephone_code: 691,
  },
  {
    iso_alpha2: 'MD',
    iso_alpha3: 'MDA',
    accepted: true,
    card_partner_accepted: false,
    name_fr: 'Moldavie',
    name_en: 'Moldova',
    name_es: 'Moldavia',
    name_de: 'Moldawien',
    name_it: 'Moldavia',
    telephone_code: 373,
  },
  {
    iso_alpha2: 'MC',
    iso_alpha3: 'MCO',
    accepted: true,
    card_partner_accepted: false,
    name_fr: 'Monaco',
    name_en: 'Monaco',
    name_es: 'Mónaco',
    name_de: 'Monaco',
    name_it: 'Montecarlo',
    telephone_code: 377,
  },
  {
    iso_alpha2: 'MN',
    iso_alpha3: 'MNG',
    accepted: false,
    card_partner_accepted: false,
    name_fr: 'Mongolie',
    name_en: 'Mongolia',
    name_es: 'Mongolia',
    name_de: 'Mongolei',
    name_it: 'Mongolia',
    telephone_code: 976,
  },
  {
    iso_alpha2: 'ME',
    iso_alpha3: 'MNE',
    accepted: true,
    card_partner_accepted: false,
    name_fr: 'Monténégro',
    name_en: 'Montenegro',
    name_es: 'Montenegro',
    name_de: 'Montenegro',
    name_it: 'Montenegro',
    telephone_code: 382,
  },
  {
    iso_alpha2: 'MS',
    iso_alpha3: 'MSR',
    accepted: true,
    card_partner_accepted: false,
    name_fr: 'Montserrat',
    name_en: 'Montserrat',
    name_es: 'Montserrat',
    name_de: 'Montserrat',
    name_it: 'Montserrat',
    telephone_code: 1664,
  },
  {
    iso_alpha2: 'MA',
    iso_alpha3: 'MAR',
    accepted: true,
    card_partner_accepted: false,
    name_fr: 'Maroc',
    name_en: 'Morocco',
    name_es: 'Marruecos',
    name_de: 'Marokko',
    name_it: 'Marocco',
    telephone_code: 212,
  },
  {
    iso_alpha2: 'MZ',
    iso_alpha3: 'MOZ',
    accepted: true,
    card_partner_accepted: false,
    name_fr: 'Mozambique',
    name_en: 'Mozambique',
    name_es: 'Mozambique',
    name_de: 'Mosambik',
    name_it: 'Mozambico',
    telephone_code: 258,
  },
  {
    iso_alpha2: 'MM',
    iso_alpha3: 'MMR',
    accepted: false,
    card_partner_accepted: false,
    name_fr: 'Birmanie',
    name_en: 'Myanmar',
    name_es: 'Birmania',
    name_de: 'Myanmar',
    name_it: 'Birmania',
    telephone_code: 95,
  },
  {
    iso_alpha2: 'NA',
    iso_alpha3: 'NAM',
    accepted: true,
    card_partner_accepted: false,
    name_fr: 'Namibie',
    name_en: 'Namibia',
    name_es: 'Namibia',
    name_de: 'Namibia',
    name_it: 'Namibia',
    telephone_code: 264,
  },
  {
    iso_alpha2: 'NR',
    iso_alpha3: 'NRU',
    accepted: true,
    card_partner_accepted: false,
    name_fr: 'Nauru',
    name_en: 'Nauru',
    name_es: 'Nauru',
    name_de: 'Nauru',
    name_it: 'Nauru',
    telephone_code: 674,
  },
  {
    iso_alpha2: 'NP',
    iso_alpha3: 'NPL',
    accepted: true,
    card_partner_accepted: false,
    name_fr: 'Népal',
    name_en: 'Nepal',
    name_es: 'Nepal',
    name_de: 'Nepal',
    name_it: 'Nepal',
    telephone_code: 977,
  },
  {
    iso_alpha2: 'NL',
    iso_alpha3: 'NLD',
    accepted: true,
    card_partner_accepted: true,
    name_fr: 'Pays-Bas',
    name_en: 'Netherlands',
    name_es: 'Países Bajos',
    name_de: 'Niederlande',
    name_it: 'Paesi Bassi',
    telephone_code: 31,
  },
  {
    iso_alpha2: 'NC',
    iso_alpha3: 'NCL',
    accepted: true,
    card_partner_accepted: true,
    name_fr: 'Nouvelle-Calédonie',
    name_en: 'New Caledonia',
    name_es: 'Nueva Caledonia',
    name_de: 'Neukaledonien',
    name_it: 'Nuova Caledonia',
    telephone_code: 687,
  },
  {
    iso_alpha2: 'NZ',
    iso_alpha3: 'NZL',
    accepted: true,
    card_partner_accepted: false,
    name_fr: 'Nouvelle-Zélande',
    name_en: 'New Zealand',
    name_es: 'Nueva Zelanda',
    name_de: 'Neuseeland',
    name_it: 'Nuova Zelanda',
    telephone_code: 64,
  },
  {
    iso_alpha2: 'NI',
    iso_alpha3: 'NIC',
    accepted: false,
    card_partner_accepted: false,
    name_fr: 'Nicaragua',
    name_en: 'Nicaragua',
    name_es: 'Nicaragua',
    name_de: 'Nicaragua',
    name_it: 'Nicaragua',
    telephone_code: 505,
  },
  {
    iso_alpha2: 'NE',
    iso_alpha3: 'NER',
    accepted: true,
    card_partner_accepted: false,
    name_fr: 'Niger',
    name_en: 'Niger',
    name_es: 'Níger',
    name_de: 'Niger',
    name_it: 'Niger',
    telephone_code: 227,
  },
  {
    iso_alpha2: 'NG',
    iso_alpha3: 'NGA',
    accepted: true,
    card_partner_accepted: false,
    name_fr: 'Nigeria',
    name_en: 'Nigeria',
    name_es: 'Nigeria',
    name_de: 'Nigeria',
    name_it: 'Nigeria',
    telephone_code: 234,
  },
  {
    iso_alpha2: 'NU',
    iso_alpha3: 'NIU',
    accepted: true,
    card_partner_accepted: false,
    name_fr: 'Niue',
    name_en: 'Niue',
    name_es: 'Niue',
    name_de: 'Niue',
    name_it: 'Niue',
    telephone_code: 683,
  },
  {
    iso_alpha2: 'NF',
    iso_alpha3: 'NFK',
    accepted: true,
    card_partner_accepted: false,
    name_fr: 'Île Norfolk',
    name_en: 'Norfolk Island',
    name_es: 'Isla Norfolk',
    name_de: 'Norfolkinsel',
    name_it: 'Isola Norfolk',
    telephone_code: null,
  },
  {
    iso_alpha2: 'MP',
    iso_alpha3: 'MNP',
    accepted: true,
    card_partner_accepted: false,
    name_fr: 'Îles Mariannes du Nord',
    name_en: 'Northern Mariana Islands',
    name_es: 'Islas Marianas del Norte',
    name_de: 'Nördliche Marianen',
    name_it: 'Isole Marianne Settentrionali',
    telephone_code: 1670,
  },
  {
    iso_alpha2: 'NO',
    iso_alpha3: 'NOR',
    accepted: true,
    card_partner_accepted: true,
    name_fr: 'Norvège',
    name_en: 'Norway',
    name_es: 'Noruega',
    name_de: 'Norwegen',
    name_it: 'Norvegia',
    telephone_code: 47,
  },
  {
    iso_alpha2: 'OM',
    iso_alpha3: 'OMN',
    accepted: false,
    card_partner_accepted: false,
    name_fr: 'Oman',
    name_en: 'Oman',
    name_es: 'Omán',
    name_de: 'Oman',
    name_it: 'Oman',
    telephone_code: 968,
  },
  {
    iso_alpha2: 'PK',
    iso_alpha3: 'PAK',
    accepted: false,
    card_partner_accepted: false,
    name_fr: 'Pakistan',
    name_en: 'Pakistan',
    name_es: 'Pakistán',
    name_de: 'Pakistan',
    name_it: 'Pakistan',
    telephone_code: 92,
  },
  {
    iso_alpha2: 'PW',
    iso_alpha3: 'PLW',
    accepted: false,
    card_partner_accepted: false,
    name_fr: 'Palaos',
    name_en: 'Palau',
    name_es: 'Palaos',
    name_de: 'Palau',
    name_it: 'Palau',
    telephone_code: 680,
  },
  {
    iso_alpha2: 'PS',
    iso_alpha3: 'PSE',
    accepted: true,
    card_partner_accepted: false,
    name_fr: 'Autorité Palestinienne',
    name_en: 'Palestinian Territory',
    name_es: 'Palestina',
    name_de: 'Palästinensische Autonomiegebiete',
    name_it: 'Palestina',
    telephone_code: null,
  },
  {
    iso_alpha2: 'PA',
    iso_alpha3: 'PAN',
    accepted: false,
    card_partner_accepted: false,
    name_fr: 'Panama',
    name_en: 'Panama',
    name_es: 'Panamá',
    name_de: 'Panama',
    name_it: 'Panama',
    telephone_code: 507,
  },
  {
    iso_alpha2: 'PG',
    iso_alpha3: 'PNG',
    accepted: true,
    card_partner_accepted: false,
    name_fr: 'Papouasie-Nouvelle-Guinée',
    name_en: 'Papua New Guinea',
    name_es: 'Papúa Nueva Guinea',
    name_de: 'Papua-Neuguinea',
    name_it: 'Papua Nuova Guinea',
    telephone_code: 675,
  },
  {
    iso_alpha2: 'PY',
    iso_alpha3: 'PRY',
    accepted: true,
    card_partner_accepted: false,
    name_fr: 'Paraguay',
    name_en: 'Paraguay',
    name_es: 'Paraguay',
    name_de: 'Paraguay',
    name_it: 'Paraguay',
    telephone_code: 595,
  },
  {
    iso_alpha2: 'PE',
    iso_alpha3: 'PER',
    accepted: true,
    card_partner_accepted: false,
    name_fr: 'Pérou',
    name_en: 'Peru',
    name_es: 'Perú',
    name_de: 'Peru',
    name_it: 'Peru',
    telephone_code: 51,
  },
  {
    iso_alpha2: 'PH',
    iso_alpha3: 'PHL',
    accepted: true,
    card_partner_accepted: false,
    name_fr: 'Philippines',
    name_en: 'Philippines',
    name_es: 'Filipinas',
    name_de: 'Philippinen',
    name_it: 'Filippine',
    telephone_code: 63,
  },
  {
    iso_alpha2: 'PN',
    iso_alpha3: 'PCN',
    accepted: true,
    card_partner_accepted: false,
    name_fr: 'Îles Pitcairn',
    name_en: 'Pitcairn',
    name_es: 'Islas Pitcairn',
    name_de: 'Pitcairn',
    name_it: 'Isola di Pitcairn',
    telephone_code: 870,
  },
  {
    iso_alpha2: 'PL',
    iso_alpha3: 'POL',
    accepted: true,
    card_partner_accepted: true,
    name_fr: 'Pologne',
    name_en: 'Poland',
    name_es: 'Polonia',
    name_de: 'Polen',
    name_it: 'Polonia',
    telephone_code: 48,
  },
  {
    iso_alpha2: 'PT',
    iso_alpha3: 'PRT',
    accepted: true,
    card_partner_accepted: true,
    name_fr: 'Portugal',
    name_en: 'Portugal',
    name_es: 'Portugal',
    name_de: 'Portugal',
    name_it: 'Portogallo',
    telephone_code: 351,
  },
  {
    iso_alpha2: 'PR',
    iso_alpha3: 'PRI',
    accepted: true,
    card_partner_accepted: false,
    name_fr: 'Porto Rico',
    name_en: 'Puerto Rico',
    name_es: 'Puerto Rico',
    name_de: 'Puerto Rico',
    name_it: 'Porto Rico',
    telephone_code: 1,
  },
  {
    iso_alpha2: 'QA',
    iso_alpha3: 'QAT',
    accepted: true,
    card_partner_accepted: false,
    name_fr: 'Qatar',
    name_en: 'Qatar',
    name_es: 'Catar',
    name_de: 'Katar',
    name_it: 'Qatar',
    telephone_code: 974,
  },
  {
    iso_alpha2: 'RE',
    iso_alpha3: 'REU',
    accepted: true,
    card_partner_accepted: true,
    name_fr: 'La Réunion',
    name_en: 'Réunion',
    name_es: 'La Reunión',
    name_de: 'La Réunion',
    name_it: 'Reunion',
    telephone_code: null,
  },
  {
    iso_alpha2: 'RO',
    iso_alpha3: 'ROU',
    accepted: true,
    card_partner_accepted: true,
    name_fr: 'Roumanie',
    name_en: 'Romania',
    name_es: 'Rumanía',
    name_de: 'Rumänien',
    name_it: 'Romania',
    telephone_code: 40,
  },
  {
    iso_alpha2: 'RU',
    iso_alpha3: 'RUS',
    accepted: true,
    card_partner_accepted: false,
    name_fr: 'Russie',
    name_en: 'Russian Federation',
    name_es: 'Rusia',
    name_de: 'Russland',
    name_it: 'Russia',
    telephone_code: 7,
  },
  {
    iso_alpha2: 'RW',
    iso_alpha3: 'RWA',
    accepted: true,
    card_partner_accepted: false,
    name_fr: 'Rwanda',
    name_en: 'Rwanda',
    name_es: 'Ruanda',
    name_de: 'Ruanda',
    name_it: 'Ruanda',
    telephone_code: 250,
  },
  {
    iso_alpha2: 'BL',
    iso_alpha3: 'BLM',
    accepted: true,
    card_partner_accepted: true,
    name_fr: 'Saint-Barthélemy',
    name_en: 'Saint Barthélemy',
    name_es: 'San Bartolomé',
    name_de: 'Saint-Barthélemy',
    name_it: 'Saint Barthelemy',
    telephone_code: 590,
  },
  {
    iso_alpha2: 'SH',
    iso_alpha3: 'SHN',
    accepted: true,
    card_partner_accepted: false,
    name_fr: 'Sainte-Hélène',
    name_en: 'Saint Helena',
    name_es: 'Santa Elena',
    name_de: 'St. Helena',
    name_it: 'Sant Elena',
    telephone_code: 290,
  },
  {
    iso_alpha2: 'KN',
    iso_alpha3: 'KNA',
    accepted: true,
    card_partner_accepted: false,
    name_fr: 'Saint-Christophe-et-Niévès',
    name_en: 'Saint Kitts and Nevis',
    name_es: 'San Cristóbal y Nieves',
    name_de: 'St. Kitts und Nevis',
    name_it: 'Saint Kitts e Nevis',
    telephone_code: 1869,
  },
  {
    iso_alpha2: 'LC',
    iso_alpha3: 'LCA',
    accepted: true,
    card_partner_accepted: false,
    name_fr: 'Sainte-Lucie',
    name_en: 'Saint Lucia',
    name_es: 'Santa Lucía',
    name_de: 'St. Lucia',
    name_it: 'Santa Lucia',
    telephone_code: 1758,
  },
  {
    iso_alpha2: 'MF',
    iso_alpha3: 'MAF',
    accepted: true,
    card_partner_accepted: true,
    name_fr: 'Saint-Martin (Antilles françaises)',
    name_en: 'Saint Martin (French part)',
    name_es: 'San Martín (Antillas Francesas)',
    name_de: 'Saint-Martin (französische Antillen)',
    name_it: 'Saint-Martin',
    telephone_code: 1599,
  },
  {
    iso_alpha2: 'PM',
    iso_alpha3: 'SPM',
    accepted: true,
    card_partner_accepted: true,
    name_fr: 'Saint-Pierre-et-Miquelon',
    name_en: 'Saint Pierre and Miquelon',
    name_es: 'San Pedro y Miquelón',
    name_de: 'Saint-Pierre und Miquelon',
    name_it: 'Saint-Pierre e Miquelon',
    telephone_code: 508,
  },
  {
    iso_alpha2: 'VC',
    iso_alpha3: 'VCT',
    accepted: true,
    card_partner_accepted: false,
    name_fr: 'Saint-Vincent-et-les-Grenadines',
    name_en: 'Saint Vincent and the Grenadines',
    name_es: 'San Vicente y las Granadinas',
    name_de: 'St. Vincent und die Grenadinen',
    name_it: 'Saint Vincent e Grenadine',
    telephone_code: 1784,
  },
  {
    iso_alpha2: 'WS',
    iso_alpha3: 'WSM',
    accepted: false,
    card_partner_accepted: false,
    name_fr: 'Samoa',
    name_en: 'Samoa',
    name_es: 'Samoa',
    name_de: 'Samoa',
    name_it: 'Samoa',
    telephone_code: 685,
  },
  {
    iso_alpha2: 'SM',
    iso_alpha3: 'SMR',
    accepted: true,
    card_partner_accepted: false,
    name_fr: 'Saint-Marin',
    name_en: 'San Marino',
    name_es: 'San Marino',
    name_de: 'San Marino',
    name_it: 'San Marino',
    telephone_code: 378,
  },
  {
    iso_alpha2: 'ST',
    iso_alpha3: 'STP',
    accepted: true,
    card_partner_accepted: false,
    name_fr: 'Sao Tomé-et-Principe',
    name_en: 'Sao Tome and Principe',
    name_es: 'Santo Tomé y Príncipe',
    name_de: 'São Tomé und Príncipe',
    name_it: 'Sao Tome e Principe',
    telephone_code: 239,
  },
  {
    iso_alpha2: 'SA',
    iso_alpha3: 'SAU',
    accepted: false,
    card_partner_accepted: false,
    name_fr: 'Arabie saoudite',
    name_en: 'Saudi Arabia',
    name_es: 'Arabia Saudí',
    name_de: 'Saudi-Arabien',
    name_it: 'Arabia Saudita',
    telephone_code: 966,
  },
  {
    iso_alpha2: 'SN',
    iso_alpha3: 'SEN',
    accepted: false,
    card_partner_accepted: false,
    name_fr: 'Sénégal',
    name_en: 'Senegal',
    name_es: 'Senegal',
    name_de: 'Senegal',
    name_it: 'Senegal',
    telephone_code: 221,
  },
  {
    iso_alpha2: 'RS',
    iso_alpha3: 'SRB',
    accepted: true,
    card_partner_accepted: false,
    name_fr: 'Serbie',
    name_en: 'Serbia',
    name_es: 'Serbia',
    name_de: 'Serbien',
    name_it: 'Serbia',
    telephone_code: 381,
  },
  {
    iso_alpha2: 'SC',
    iso_alpha3: 'SYC',
    accepted: false,
    card_partner_accepted: false,
    name_fr: 'Seychelles',
    name_en: 'Seychelles',
    name_es: 'Seychelles',
    name_de: 'Seychellen',
    name_it: 'Seychelles',
    telephone_code: 248,
  },
  {
    iso_alpha2: 'SL',
    iso_alpha3: 'SLE',
    accepted: true,
    card_partner_accepted: false,
    name_fr: 'Sierra Leone',
    name_en: 'Sierra Leone',
    name_es: 'Sierra Leona',
    name_de: 'Sierra Leone',
    name_it: 'Sierra Leone',
    telephone_code: 232,
  },
  {
    iso_alpha2: 'SG',
    iso_alpha3: 'SGP',
    accepted: true,
    card_partner_accepted: true,
    name_fr: 'Singapour',
    name_en: 'Singapore',
    name_es: 'Singapur',
    name_de: 'Singapur',
    name_it: 'Singapore',
    telephone_code: 65,
  },
  {
    iso_alpha2: 'SX',
    iso_alpha3: 'SXM',
    accepted: true,
    card_partner_accepted: false,
    name_fr: 'Saint-Martin',
    name_en: 'Sint Maarten (Dutch part)',
    name_es: 'San Martín (Antillas Holandesas)',
    name_de: 'Saint-Martin (niederländische Antillen)',
    name_it: 'Sint Maarten',
    telephone_code: null,
  },
  {
    iso_alpha2: 'SK',
    iso_alpha3: 'SVK',
    accepted: true,
    card_partner_accepted: true,
    name_fr: 'Slovaquie',
    name_en: 'Slovakia',
    name_es: 'Eslovaquia',
    name_de: 'Slowakei',
    name_it: 'Slovacchia',
    telephone_code: 421,
  },
  {
    iso_alpha2: 'SI',
    iso_alpha3: 'SVN',
    accepted: true,
    card_partner_accepted: true,
    name_fr: 'Slovénie',
    name_en: 'Slovenia',
    name_es: 'Eslovenia',
    name_de: 'Slowenien',
    name_it: 'Slovenia',
    telephone_code: 386,
  },
  {
    iso_alpha2: 'SB',
    iso_alpha3: 'SLB',
    accepted: true,
    card_partner_accepted: false,
    name_fr: 'Salomon',
    name_en: 'Solomon Islands',
    name_es: 'Islas Salomón',
    name_de: 'Salomonen',
    name_it: 'Isole Solomone',
    telephone_code: 677,
  },
  {
    iso_alpha2: 'SO',
    iso_alpha3: 'SOM',
    accepted: true,
    card_partner_accepted: false,
    name_fr: 'Somalie',
    name_en: 'Somalia',
    name_es: 'Somalia',
    name_de: 'Somalia',
    name_it: 'Somalia',
    telephone_code: 252,
  },
  {
    iso_alpha2: 'ZA',
    iso_alpha3: 'ZAF',
    accepted: true,
    card_partner_accepted: true,
    name_fr: 'Afrique du Sud',
    name_en: 'South Africa',
    name_es: 'Sudáfrica',
    name_de: 'Südafrika',
    name_it: 'Sudafrica',
    telephone_code: 27,
  },
  {
    iso_alpha2: 'GS',
    iso_alpha3: 'SGS',
    accepted: true,
    card_partner_accepted: false,
    name_fr: 'Géorgie du Sud-et-les Îles Sandwich du Sud',
    name_en: 'South Georgia and the South Sandwich Islands',
    name_es: 'Islas Georgias del Sur y Sándwich del Sur',
    name_de: 'Südgeorgien und die Südlichen Sandwichinseln',
    name_it: 'Georgia del Sud e Isole Sandwich del Sud',
    telephone_code: null,
  },
  {
    iso_alpha2: 'SS',
    iso_alpha3: 'SSD',
    accepted: true,
    card_partner_accepted: false,
    name_fr: 'Soudan du Sud',
    name_en: 'South Sudan',
    name_es: 'Sudán del Sur',
    name_de: 'Südsudan',
    name_it: 'Sud Sudan',
    telephone_code: null,
  },
  {
    iso_alpha2: 'ES',
    iso_alpha3: 'ESP',
    accepted: true,
    card_partner_accepted: true,
    name_fr: 'Espagne',
    name_en: 'Spain',
    name_es: 'España',
    name_de: 'Spanien',
    name_it: 'Spagna',
    telephone_code: 34,
  },
  {
    iso_alpha2: 'LK',
    iso_alpha3: 'LKA',
    accepted: false,
    card_partner_accepted: false,
    name_fr: 'Sri Lanka',
    name_en: 'Sri Lanka',
    name_es: 'Sri Lanka',
    name_de: 'Sri Lanka',
    name_it: 'Sri Lanka',
    telephone_code: 94,
  },
  {
    iso_alpha2: 'SD',
    iso_alpha3: 'SDN',
    accepted: false,
    card_partner_accepted: false,
    name_fr: 'Soudan',
    name_en: 'Sudan',
    name_es: 'Sudán',
    name_de: 'Sudan',
    name_it: 'Sudan',
    telephone_code: 249,
  },
  {
    iso_alpha2: 'SR',
    iso_alpha3: 'SUR',
    accepted: true,
    card_partner_accepted: false,
    name_fr: 'Suriname',
    name_en: 'Suriname',
    name_es: 'Surinam',
    name_de: 'Suriname',
    name_it: 'Suriname',
    telephone_code: 597,
  },
  {
    iso_alpha2: 'SJ',
    iso_alpha3: 'SJM',
    accepted: true,
    card_partner_accepted: false,
    name_fr: 'Svalbard et île Jan Mayen',
    name_en: 'Svalbard and Jan Mayen',
    name_es: 'Svalbard y Jan Mayen',
    name_de: 'Spitzbergen und Jan Mayen',
    name_it: 'Svalbard e Jan Mayen',
    telephone_code: null,
  },
  {
    iso_alpha2: 'SZ',
    iso_alpha3: 'SWZ',
    accepted: true,
    card_partner_accepted: false,
    name_fr: 'Swaziland',
    name_en: 'Swaziland',
    name_es: 'Suazilandia',
    name_de: 'Swaziland',
    name_it: 'Swaziland',
    telephone_code: 268,
  },
  {
    iso_alpha2: 'SE',
    iso_alpha3: 'SWE',
    accepted: true,
    card_partner_accepted: true,
    name_fr: 'Suède',
    name_en: 'Sweden',
    name_es: 'Suecia',
    name_de: 'Schweden',
    name_it: 'Svezia',
    telephone_code: 46,
  },
  {
    iso_alpha2: 'CH',
    iso_alpha3: 'CHE',
    accepted: true,
    card_partner_accepted: true,
    name_fr: 'Suisse',
    name_en: 'Switzerland',
    name_es: 'Suiza',
    name_de: 'Schweiz',
    name_it: 'Svizzera',
    telephone_code: 41,
  },
  {
    iso_alpha2: 'SY',
    iso_alpha3: 'SYR',
    accepted: false,
    card_partner_accepted: false,
    name_fr: 'Syrie',
    name_en: 'Syrian Arab Republic',
    name_es: 'Siria',
    name_de: 'Arabische Republik Syrien',
    name_it: 'Siria',
    telephone_code: 963,
  },
  {
    iso_alpha2: 'TW',
    iso_alpha3: 'TWN',
    accepted: true,
    card_partner_accepted: false,
    name_fr: 'Taïwan',
    name_en: 'Taiwan',
    name_es: 'Taiwán',
    name_de: 'Taiwan (Volksrepublik China)',
    name_it: 'Taiwan',
    telephone_code: 886,
  },
  {
    iso_alpha2: 'TJ',
    iso_alpha3: 'TJK',
    accepted: true,
    card_partner_accepted: false,
    name_fr: 'Tadjikistan',
    name_en: 'Tajikistan',
    name_es: 'Tayikistán',
    name_de: 'Tadschikistan',
    name_it: 'Tagikistan',
    telephone_code: 992,
  },
  {
    iso_alpha2: 'TZ',
    iso_alpha3: 'TZA',
    accepted: true,
    card_partner_accepted: false,
    name_fr: 'Tanzanie',
    name_en: 'Tanzania',
    name_es: 'Tanzania',
    name_de: 'Vereinigte Republik Tansania',
    name_it: 'Tanzania',
    telephone_code: 255,
  },
  {
    iso_alpha2: 'TH',
    iso_alpha3: 'THA',
    accepted: true,
    card_partner_accepted: false,
    name_fr: 'Thaïlande',
    name_en: 'Thailand',
    name_es: 'Tailandia',
    name_de: 'Thailand',
    name_it: 'Tailandia',
    telephone_code: 66,
  },
  {
    iso_alpha2: 'TL',
    iso_alpha3: 'TLS',
    accepted: true,
    card_partner_accepted: false,
    name_fr: 'Timor oriental',
    name_en: 'Timor-Leste',
    name_es: 'Timor Oriental',
    name_de: 'Osttimor',
    name_it: 'Timor est',
    telephone_code: 670,
  },
  {
    iso_alpha2: 'TG',
    iso_alpha3: 'TGO',
    accepted: true,
    card_partner_accepted: false,
    name_fr: 'Togo',
    name_en: 'Togo',
    name_es: 'Togo',
    name_de: 'Togo',
    name_it: 'Togo',
    telephone_code: 228,
  },
  {
    iso_alpha2: 'TK',
    iso_alpha3: 'TKL',
    accepted: true,
    card_partner_accepted: false,
    name_fr: 'Tokelau',
    name_en: 'Tokelau',
    name_es: 'Tokelau',
    name_de: 'Tokelau',
    name_it: 'Tokelau',
    telephone_code: 690,
  },
  {
    iso_alpha2: 'TO',
    iso_alpha3: 'TON',
    accepted: true,
    card_partner_accepted: false,
    name_fr: 'Tonga',
    name_en: 'Tonga',
    name_es: 'Tonga',
    name_de: 'Tonga',
    name_it: 'Tonga',
    telephone_code: 676,
  },
  {
    iso_alpha2: 'TT',
    iso_alpha3: 'TTO',
    accepted: false,
    card_partner_accepted: false,
    name_fr: 'Trinité-et-Tobago',
    name_en: 'Trinidad and Tobago',
    name_es: 'Trinidad y Tobago',
    name_de: 'Trinidad und Tobago',
    name_it: 'Trinidad e Tobago',
    telephone_code: 1868,
  },
  {
    iso_alpha2: 'TN',
    iso_alpha3: 'TUN',
    accepted: true,
    card_partner_accepted: false,
    name_fr: 'Tunisie',
    name_en: 'Tunisia',
    name_es: 'Túnez',
    name_de: 'Tunesien',
    name_it: 'Tunisia',
    telephone_code: 216,
  },
  {
    iso_alpha2: 'TR',
    iso_alpha3: 'TUR',
    accepted: true,
    card_partner_accepted: false,
    name_fr: 'Turquie',
    name_en: 'Turkey',
    name_es: 'Turquía',
    name_de: 'Türkei',
    name_it: 'Turchia',
    telephone_code: 90,
  },
  {
    iso_alpha2: 'TM',
    iso_alpha3: 'TKM',
    accepted: true,
    card_partner_accepted: false,
    name_fr: 'Turkménistan',
    name_en: 'Turkmenistan',
    name_es: 'Turkmenistán',
    name_de: 'Turkmenistan',
    name_it: 'Turkmenistan',
    telephone_code: 993,
  },
  {
    iso_alpha2: 'TC',
    iso_alpha3: 'TCA',
    accepted: true,
    card_partner_accepted: false,
    name_fr: 'Îles Turques-et-Caïques',
    name_en: 'Turks and Caicos Islands',
    name_es: 'Islas Turcas y Caicos',
    name_de: 'Turks- und Caicosinseln',
    name_it: 'Isole Turks e Caicos',
    telephone_code: 1649,
  },
  {
    iso_alpha2: 'TV',
    iso_alpha3: 'TUV',
    accepted: true,
    card_partner_accepted: false,
    name_fr: 'Tuvalu',
    name_en: 'Tuvalu',
    name_es: 'Tuvalu',
    name_de: 'Tuvalu',
    name_it: 'Tuvalu',
    telephone_code: 688,
  },
  {
    iso_alpha2: 'UG',
    iso_alpha3: 'UGA',
    accepted: false,
    card_partner_accepted: false,
    name_fr: 'Ouganda',
    name_en: 'Uganda',
    name_es: 'Uganda',
    name_de: 'Uganda',
    name_it: 'Uganda',
    telephone_code: 256,
  },
  {
    iso_alpha2: 'UA',
    iso_alpha3: 'UKR',
    accepted: true,
    card_partner_accepted: false,
    name_fr: 'Ukraine',
    name_en: 'Ukraine',
    name_es: 'Ucrania',
    name_de: 'Ukraine',
    name_it: 'Ucraina',
    telephone_code: 380,
  },
  {
    iso_alpha2: 'AE',
    iso_alpha3: 'ARE',
    accepted: true,
    card_partner_accepted: false,
    name_fr: 'Émirats arabes unis',
    name_en: 'United Arab Emirates',
    name_es: 'Emiratos Árabes Unidos',
    name_de: 'Vereinigte Arabische Emirate',
    name_it: 'Emirati Arabi Uniti',
    telephone_code: 971,
  },
  {
    iso_alpha2: 'GB',
    iso_alpha3: 'GBR',
    accepted: true,
    card_partner_accepted: true,
    name_fr: 'Royaume-Uni',
    name_en: 'United Kingdom',
    name_es: 'Reino Unido',
    name_de: 'Vereinigtes Königreich',
    name_it: 'Regno Unito',
    telephone_code: 44,
  },
  {
    iso_alpha2: 'US',
    iso_alpha3: 'USA',
    accepted: false,
    card_partner_accepted: false,
    name_fr: 'États-Unis',
    name_en: 'United States',
    name_es: 'Estados Unidos de América',
    name_de: 'Vereinigte Staaten von Amerika',
    name_it: 'Stati Uniti',
    telephone_code: 1,
  },
  {
    iso_alpha2: 'UM',
    iso_alpha3: 'UMI',
    accepted: true,
    card_partner_accepted: false,
    name_fr: 'Îles mineures éloignées des États-Unis',
    name_en: 'United States Minor Outlying Islands',
    name_es: 'Islas Ultramarinas Menores de Estados Unidos',
    name_de: 'United States Minor Outlying Islands',
    name_it: 'Isole Minori degli Stati Uniti',
    telephone_code: null,
  },
  {
    iso_alpha2: 'UY',
    iso_alpha3: 'URY',
    accepted: true,
    card_partner_accepted: false,
    name_fr: 'Uruguay',
    name_en: 'Uruguay',
    name_es: 'Uruguay',
    name_de: 'Uruguay',
    name_it: 'Uruguay',
    telephone_code: 598,
  },
  {
    iso_alpha2: 'UZ',
    iso_alpha3: 'UZB',
    accepted: true,
    card_partner_accepted: false,
    name_fr: 'Ouzbékistan',
    name_en: 'Uzbekistan',
    name_es: 'Uzbekistán',
    name_de: 'Usbekistan',
    name_it: 'Uzbekistan',
    telephone_code: 998,
  },
  {
    iso_alpha2: 'VU',
    iso_alpha3: 'VUT',
    accepted: false,
    card_partner_accepted: false,
    name_fr: 'Vanuatu',
    name_en: 'Vanuatu',
    name_es: 'Vanuatu',
    name_de: 'Vanuatu',
    name_it: 'Vanuatu',
    telephone_code: 678,
  },
  {
    iso_alpha2: 'VE',
    iso_alpha3: 'VEN',
    accepted: true,
    card_partner_accepted: false,
    name_fr: 'Venezuela',
    name_en: 'Venezuela',
    name_es: 'Venezuela',
    name_de: 'Bolivarische Republik Venezuela',
    name_it: 'Venezuela',
    telephone_code: 58,
  },
  {
    iso_alpha2: 'VN',
    iso_alpha3: 'VNM',
    accepted: true,
    card_partner_accepted: false,
    name_fr: 'Viêt Nam',
    name_en: 'Viet Nam',
    name_es: 'Vietnam',
    name_de: 'Vietnam',
    name_it: 'Vietnam',
    telephone_code: 84,
  },
  {
    iso_alpha2: 'VG',
    iso_alpha3: 'VGB',
    accepted: false,
    card_partner_accepted: false,
    name_fr: 'Îles Vierges britanniques',
    name_en: 'Virgin Islands (UK)',
    name_es: 'Islas Vírgenes Británicas',
    name_de: 'Britische Jungferninseln',
    name_it: 'Isole Vergini britanniche',
    telephone_code: 1284,
  },
  {
    iso_alpha2: 'VI',
    iso_alpha3: 'VIR',
    accepted: false,
    card_partner_accepted: false,
    name_fr: 'Îles Vierges des Américaines',
    name_en: 'Virgin Islands (US)',
    name_es: 'Islas Vírgenes de los Estados Unidos',
    name_de: 'Amerikanische Jungferninseln',
    name_it: 'Isole Vergini americane',
    telephone_code: 1340,
  },
  {
    iso_alpha2: 'WF',
    iso_alpha3: 'WLF',
    accepted: true,
    card_partner_accepted: true,
    name_fr: 'Wallis-et-Futuna',
    name_en: 'Wallis and Futuna',
    name_es: 'Wallis y Futuna',
    name_de: 'Wallis und Futuna',
    name_it: 'Isole Wallis e Futuna',
    telephone_code: 681,
  },
  {
    iso_alpha2: 'EH',
    iso_alpha3: 'ESH',
    accepted: true,
    card_partner_accepted: false,
    name_fr: 'Sahara occidental',
    name_en: 'Western Sahara',
    name_es: 'Sáhara Occidental',
    name_de: 'Westsahara',
    name_it: 'Sahara Occidentale',
    telephone_code: null,
  },
  {
    iso_alpha2: 'YE',
    iso_alpha3: 'YEM',
    accepted: false,
    card_partner_accepted: false,
    name_fr: 'Yémen',
    name_en: 'Yemen',
    name_es: 'Yemen',
    name_de: 'Jemen',
    name_it: 'Yémen',
    telephone_code: 967,
  },
  {
    iso_alpha2: 'ZM',
    iso_alpha3: 'ZMB',
    accepted: true,
    card_partner_accepted: false,
    name_fr: 'Zambie',
    name_en: 'Zambia',
    name_es: 'Zambia',
    name_de: 'Sambia',
    name_it: 'Zambia',
    telephone_code: 260,
  },
  {
    iso_alpha2: 'ZW',
    iso_alpha3: 'ZWE',
    accepted: false,
    card_partner_accepted: false,
    name_fr: 'Zimbabwe',
    name_en: 'Zimbabwe',
    name_es: 'Zimbabue',
    name_de: 'Simbabwe',
    name_it: 'Zimbabwe',
    telephone_code: 263,
  },
];
