/**
 * Copyright (c) Paymium.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root of this projects source tree.
 */

import './globals.css';
import '@/style.config';
import type { Metadata } from 'next';
import { PropsWithChildren } from 'react';
import { Registry } from '@crossed/styled';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: PropsWithChildren) {
  return (
    <html lang={'en'} className={`${Registry.themeName}`}>
      <head />
      <body>{children}</body>
    </html>
  );
}
