on:
  pull_request:
    branches:
      - 'main'

permissions:
  contents: read
  id-token: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # 👇 Build steps
      - name: Set up Node.js
        uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Install dependencies
        run: pnpm install --frozen-lock
      - name: Linter
        run: pnpm lint
      - name: Build
        run: pnpm build
      - name: Build
        run: pnpm -F crossed-docs build